Repository Tour-Ranger/Tour-Ranger-Back, pull requests merged in 2023-09, with the labels that each got.

#39 [feature] 배너페이지 화면 기능추가
  src/main/java/com/tourranger/item/controller/ItemController.java
  src/main/java/com/tourranger/item/repository/ItemRepository.java
  src/main/java/com/tourranger/item/service/ItemService.java
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
  src/main/resources/templates/bannerPage.html
Labels: feature, front

#48 [refactor] ItemList조회 속도 개선
  src/main/java/com/tourranger/item/repository/ItemRepository.java
  src/main/java/com/tourranger/item/repository/ItemRepositoryCustom.java
  src/main/java/com/tourranger/item/repository/ItemRepositoryImpl.java
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
  src/main/resources/templates/bannerPage.html
Labels: refactor

#50 [Refactor] Item 필드 변경
  src/main/java/com/tourranger/common/dummy/DummyGenerator.java
  src/main/java/com/tourranger/item/dto/ItemResponseDto.java
  src/main/java/com/tourranger/item/entity/Item.java
  src/test/java/com/tourranger/common/DummyDataTest.java
  src/test/java/com/tourranger/item/ItemServiceTest.java
Labels: refactor

#55 [deploy] Tour-Ranger Early-Access Version 0.0.3
  .github/workflows/main-cd-elb.yml
Labels: deploy

#56 [Feature] 메인페이지 조회 시 상세검색(필터) 기능 추가
  src/main/java/com/tourranger/item/controller/ItemController.java
  src/main/java/com/tourranger/item/repository/ItemRepository.java
  src/main/java/com/tourranger/item/service/ItemService.java
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
  src/main/resources/templates/bannerPage.html
  src/main/resources/templates/tourItemPage.html
Labels: feature

#60 [fix] 1글자 검색 시, 조회되지 않는 문제 수정
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
Labels: fix

#63 [fix] 테스트용 LIKE문 조회 오류 수정
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
Labels: fix

#67 [feature] 멀티스레드 사용
  src/main/java/com/tourranger/TourRangerApplication.java
  src/main/java/com/tourranger/common/config/AsyncConfig.java
  src/main/java/com/tourranger/purchase/service/PurchaseServiceImpl.java
Labels: feature

#69 [feature] 회원가입, 로그인 - 멀티 로그인 방지, 레디스 - 세션 관리
  build.gradle
  src/main/java/com/tourranger/common/config/PasswordConfig.java
  src/main/java/com/tourranger/common/error/CustomErrorCode.java
  src/main/java/com/tourranger/common/security/UserDetailsImpl.java
  src/main/java/com/tourranger/common/security/UserDetailsServiceImpl.java
  src/main/java/com/tourranger/common/security/WebSecurityConfig.java
  src/main/java/com/tourranger/front/HomeController.java
  src/main/java/com/tourranger/purchase/service/PurchaseServiceImpl.java
  src/main/java/com/tourranger/user/controller/UserController.java
  src/main/java/com/tourranger/user/dto/SignupRequestDto.java
  src/main/java/com/tourranger/user/entity/User.java
  src/main/java/com/tourranger/user/entity/UserRoleEnum.java
  src/main/java/com/tourranger/user/service/UserService.java
  src/main/java/com/tourranger/user/service/UserServiceImpl.java
  src/main/resources/templates/bannerPage.html
  src/main/resources/templates/signupPage.html
Labels: feature

#27 [Feature] 검색기능에 Redis cache 적용
  build.gradle
  src/main/java/com/tourranger/TourRangerApplication.java
  src/main/java/com/tourranger/airline/controller/AirlineController.java
  src/main/java/com/tourranger/airline/service/AirlineService.java
  src/main/java/com/tourranger/airline/service/AirlineServiceImpl.java
  src/main/java/com/tourranger/common/redis/RedisCacheConfig.java
  src/main/java/com/tourranger/common/redis/RedisConfig.java
  src/main/java/com/tourranger/item/dto/ItemResponseDto.java
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
  src/main/java/com/tourranger/thumbnailImage/controller/ThumbnailImageController.java
  src/main/java/com/tourranger/thumbnailImage/service/ThumbnailImageService.java
  src/main/java/com/tourranger/thumbnailImage/service/ThumbnailImageServiceImpl.java
  src/main/java/com/tourranger/travelAgency/controller/TravelAgencyController.java
  src/main/java/com/tourranger/travelAgency/service/TravelAgencyService.java
  src/main/java/com/tourranger/travelAgency/service/TravelAgencyServiceImpl.java
Labels: feature

#72 [Update] README.md (WIP)
  README.md
Labels: documentation

#73 [deploy] Tour-Ranger Early-Access Version 0.2.0
  README.md
  build.gradle
  src/main/java/com/tourranger/TourRangerApplication.java
  src/main/java/com/tourranger/airline/controller/AirlineController.java
  src/main/java/com/tourranger/airline/service/AirlineService.java
  src/main/java/com/tourranger/airline/service/AirlineServiceImpl.java
  src/main/java/com/tourranger/common/config/PasswordConfig.java
  src/main/java/com/tourranger/common/error/CustomErrorCode.java
  src/main/java/com/tourranger/common/redis/RedisCacheConfig.java
  src/main/java/com/tourranger/common/redis/RedisConfig.java
  src/main/java/com/tourranger/common/security/UserDetailsImpl.java
  src/main/java/com/tourranger/common/security/UserDetailsServiceImpl.java
  src/main/java/com/tourranger/common/security/WebSecurityConfig.java
  src/main/java/com/tourranger/front/HomeController.java
  src/main/java/com/tourranger/item/dto/ItemResponseDto.java
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
  src/main/java/com/tourranger/purchase/service/PurchaseServiceImpl.java
  src/main/java/com/tourranger/thumbnailImage/controller/ThumbnailImageController.java
  src/main/java/com/tourranger/thumbnailImage/service/ThumbnailImageService.java
  src/main/java/com/tourranger/thumbnailImage/service/ThumbnailImageServiceImpl.java
  src/main/java/com/tourranger/travelAgency/controller/TravelAgencyController.java
  src/main/java/com/tourranger/travelAgency/service/TravelAgencyService.java
  src/main/java/com/tourranger/travelAgency/service/TravelAgencyServiceImpl.java
  src/main/java/com/tourranger/user/controller/UserController.java
  src/main/java/com/tourranger/user/dto/SignupRequestDto.java
  src/main/java/com/tourranger/user/entity/User.java
  src/main/java/com/tourranger/user/entity/UserRoleEnum.java
  src/main/java/com/tourranger/user/service/UserService.java
  src/main/java/com/tourranger/user/service/UserServiceImpl.java
  src/main/resources/templates/bannerPage.html
  src/main/resources/templates/signupPage.html
Labels: deploy

#74 [docs] README
  README.md
Labels: documentation
