Repository Tour-Ranger/Tour-Ranger-Back, pull requests merged in 2023-08, with the labels that each got.

#4 [feature] User 더미 데이터 삽입 코드 구현
  build.gradle
  src/main/java/com/tourranger/common/dummy/DummyGenerator.java
  src/main/java/com/tourranger/user/repository/UserRepository.java
  src/main/java/com/tourranger/user/repository/UserRepositoryCustom.java
  src/main/java/com/tourranger/user/repository/UserRepositoryImpl.java
  src/test/java/com/tourranger/common/DummyDataTest.java
Labels: feature

#7 [feature] Item 더미 데이터 삽입 코드 구현
  src/main/java/com/tourranger/common/dummy/DummyGenerator.java
  src/main/java/com/tourranger/item/entity/Item.java
  src/main/java/com/tourranger/item/repository/ItemRepository.java
  src/main/java/com/tourranger/item/repository/ItemRepositoryCustom.java
  src/main/java/com/tourranger/item/repository/ItemRepositoryImpl.java
  src/main/java/com/tourranger/purchase/entity/Purchase.java
  src/main/java/com/tourranger/user/entity/User.java
  src/test/java/com/tourranger/common/DummyDataTest.java
Labels: feature

#10 [feature] 구매 API
  src/main/java/com/tourranger/common/error/CustomErrorCode.java
  src/main/java/com/tourranger/item/entity/Item.java
  src/main/java/com/tourranger/purchase/controller/PurchaseController.java
  src/main/java/com/tourranger/purchase/dto/PurchaseRequestDto.java
  src/main/java/com/tourranger/purchase/repository/PurchaseRepository.java
  src/main/java/com/tourranger/purchase/repository/PurchaseRepositoryCustom.java
  src/main/java/com/tourranger/purchase/repository/PurchaseRepositoryImpl.java
  src/main/java/com/tourranger/purchase/service/PurchaseService.java
  src/main/java/com/tourranger/purchase/service/PurchaseServiceImpl.java
  src/main/java/com/tourranger/user/repository/UserRepository.java
  src/main/java/com/tourranger/user/service/UserService.java
  src/main/java/com/tourranger/user/service/UserServiceImpl.java
  src/test/java/com/tourranger/purchase/controller/PurchaseRequestDtoValidTest.java
  src/test/java/com/tourranger/purchase/service/PurchaseServiceTest.java
Labels: feature

#9 [feature] 이미지 조회 API 구현
  src/main/java/com/tourranger/common/error/CustomErrorCode.java
  src/main/java/com/tourranger/common/file/FileStore.java
  src/main/java/com/tourranger/image/Dto/ImageResponseDto.java
  src/main/java/com/tourranger/image/controller/ImageController.java
  src/main/java/com/tourranger/image/entity/Image.java
  src/main/java/com/tourranger/image/repository/ImageRepository.java
  src/main/java/com/tourranger/image/repository/ImageRepositoryCustom.java
  src/main/java/com/tourranger/image/repository/ImageRepositoryImpl.java
  src/main/java/com/tourranger/image/service/ImageService.java
  src/main/java/com/tourranger/image/service/ImageServiceImpl.java
  src/main/java/com/tourranger/item/entity/Item.java
  src/main/java/com/tourranger/item/service/ItemService.java
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
  src/main/java/com/tourranger/itemImage/entity/ItemImage.java
  src/main/java/com/tourranger/purchase/service/PurchaseServiceImpl.java
  src/main/java/com/tourranger/user/entity/User.java
Labels: feature

#12 [feature] 상품 조회 API
  src/main/java/com/tourranger/image/entity/Image.java
  src/main/java/com/tourranger/item/controller/ItemController.java
  src/main/java/com/tourranger/item/dto/ItemResponseDto.java
  src/main/java/com/tourranger/item/entity/Item.java
  src/main/java/com/tourranger/item/service/ItemService.java
  src/main/java/com/tourranger/item/service/ItemServiceImpl.java
  src/main/java/com/tourranger/purchase/service/PurchaseService.java
  src/test/java/com/tourranger/purchase/controller/PurchaseRequestDtoValidTest.java
Labels: feature

#15 [hotfix] ItemResponseDto @Getter annotation 추가
  src/main/java/com/tourranger/item/dto/ItemResponseDto.java
Labels: fix

#19 [feature] 프론트엔드 화면구현
  .github/workflows/develop-ci.yml
  src/main/java/com/tourranger/front/HomeController.java
  src/main/resources/static/image/banner.png
  src/main/resources/templates/bannerPage.html
  src/main/resources/templates/tourItemPage.html
Labels: front

#22 [feature] AWS 서버 연동 및 CD
  .github/workflows/main-cd.yml
  appspec.yml
  build.gradle
  build.gradle.kts
  scripts/deploy.sh
  scripts/start.sh
  scripts/stop.sh
Labels: CI/CD, feature

#25 [Refactor] 이미지 CRUD API
  src/main/java/com/tourranger/airline/controller/AirlineController.java
  src/main/java/com/tourranger/airline/entity/Airline.java
  src/main/java/com/tourranger/airline/repository/AirlineRepository.java
  src/main/java/com/tourranger/airline/repository/AirlineRepositoryCustom.java
  src/main/java/com/tourranger/airline/repository/AirlineRepositoryImpl.java
  src/main/java/com/tourranger/airline/service/AirlineService.java
  src/main/java/com/tourranger/airline/service/AirlineServiceImpl.java
  src/main/java/com/tourranger/common/error/CustomErrorCode.java
  src/main/java/com/tourranger/common/exception/GlobalControllerAdvice.java
  src/main/java/com/tourranger/common/file/FileStore.java
  src/main/java/com/tourranger/image/Dto/ImageResponseDto.java
  src/main/java/com/tourranger/image/controller/ImageController.java
  src/main/java/com/tourranger/image/entity/Image.java
  src/main/java/com/tourranger/image/repository/ImageRepository.java
  src/main/java/com/tourranger/image/repository/ImageRepositoryCustom.java
  src/main/java/com/tourranger/image/service/ImageService.java
  src/main/java/com/tourranger/image/service/ImageServiceImpl.java
  src/main/java/com/tourranger/item/entity/Item.java
  src/main/java/com/tourranger/thumbnailImage/controller/ThumbnailImageController.java
  src/main/java/com/tourranger/thumbnailImage/entity/ThumbnailImage.java
  src/main/java/com/tourranger/thumbnailImage/repository/ThumbnailImageRepository.java
  src/main/java/com/tourranger/thumbnailImage/repository/ThumbnailImageRepositoryCustom.java
  src/main/java/com/tourranger/thumbnailImage/repository/ThumbnailImageRepositoryImpl.java
  src/main/java/com/tourranger/thumbnailImage/service/ThumbnailImageService.java
  src/main/java/com/tourranger/thumbnailImage/service/ThumbnailImageServiceImpl.java
  src/main/java/com/tourranger/travelAgency/controller/TravelAgencyController.java
  src/main/java/com/tourranger/travelAgency/entity/TravelAgency.java
  src/main/java/com/tourranger/travelAgency/repository/TravelAgencyRepository.java
  src/main/java/com/tourranger/travelAgency/repository/TravelAgencyRepositoryCustom.java
  src/main/java/com/tourranger/travelAgency/repository/TravelAgencyRepositoryImpl.java
  src/main/java/com/tourranger/travelAgency/service/TravelAgencyService.java
  src/main/java/com/tourranger/travelAgency/service/TravelAgencyServiceImpl.java
  src/test/java/com/tourranger/common/DummyDataTest.java
Labels: refactor

#28 [Refactor] Item Entity 수정
  src/main/java/com/tourranger/airline/repository/AirlineRepository.java
  src/main/java/com/tourranger/common/dummy/DummyGenerator.java
  src/main/java/com/tourranger/item/dto/ItemResponseDto.java
  src/main/java/com/tourranger/item/entity/Item.java
  src/main/java/com/tourranger/item/repository/ItemRepository.java
  src/main/java/com/tourranger/purchase/service/PurchaseServiceImpl.java
  src/main/java/com/tourranger/thumbnailImage/repository/ThumbnailImageRepository.java
  src/main/java/com/tourranger/travelAgency/repository/TravelAgencyRepository.java
  src/test/java/com/tourranger/common/DummyDataTest.java
Labels: refactor

#33 [refactor] 프론트엔드-아이템 상세 페이지
  src/main/java/com/tourranger/front/HomeController.java
  src/main/java/com/tourranger/item/dto/ItemResponseDto.java
  src/main/resources/templates/bannerPage.html
  src/main/resources/templates/tourItemPage.html
Labels: refactor

#35 [test] 상품 조회 API 테스트코드 작성
  src/test/java/com/tourranger/item/ItemServiceTest.java
Labels: test code
